### ISSUE TITLE
Which cells do we need to extract?

### ISSUE THREAD

**Issue by Alwazir95** [Alwazir95/cad_project#2]
I'm still a bit confused as to which specific cells in the tally are we going to need. Can someone please let me know. I'm trying to start working on some of the basic core tasks. Thanks!

**Comment by mohammedscode** [comment]
I am assuming you are referring to the tally sheet in the file "41043 Tally Sheet.xls" 

To plot, we are going to need a coordinate (x,y) for each plot (vertical plot and the horizontal plot):
Vertical plot: ("X" column, "ELEV" column) 
Horizontal plot: ("X" column, _The y-value of this coordinate is a function of the cells in the "Y" column. We will need to make a separate column with the necessary formula to calculate it and use that cell to plot. I think that would be the best thing to do and then update from there. To answer your question, you can use "Y" column for now._)

Hope this helps 🚀
